#!/bin/bash

# Guide rapide pour ajouter les bandes-annonces
# Ce script affiche les instructions

echo "╔══════════════════════════════════════════════════════════╗"
echo "║       🎬 Neo4flix - Ajout des Bandes-Annonces 🎬        ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "📋 Étapes pour ajouter les bandes-annonces aux films:"
echo ""
echo "1️⃣  Assurez-vous que Neo4j est démarré"
echo "   → docker-compose up -d neo4j"
echo "   → Ou démarrage manuel de Neo4j"
echo ""
echo "2️⃣  Vérifiez que les films existent dans la base"
echo "   → Accédez à http://localhost:7474"
echo "   → Exécutez: MATCH (m:Movie) RETURN count(m)"
echo ""
echo "3️⃣  Exécutez le script d'ajout des bandes-annonces"
echo "   → cd /home/pro12x/Desktop/Projects/01Dakar/Java/neo4flix"
echo "   → ./scripts/add-trailers.sh"
echo ""
echo "4️⃣  Vérifiez que les URLs ont été ajoutées"
echo "   → Dans Neo4j Browser:"
echo "   → MATCH (m:Movie) RETURN m.title, m.trailer_url LIMIT 10"
echo ""
echo "5️⃣  Redémarrez le movie-service"
echo "   → cd movie-service"
echo "   → mvn spring-boot:run"
echo ""
echo "6️⃣  Testez dans le frontend"
echo "   → Ouvrez un film"
echo "   → Cliquez sur le bouton 'Play'"
echo "   → La bande-annonce devrait se lancer !"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "🎯 Méthode alternative (Neo4j Browser):"
echo ""
echo "Si le script bash ne fonctionne pas, vous pouvez:"
echo "1. Ouvrir Neo4j Browser (http://localhost:7474)"
echo "2. Copier le fichier scripts/add-trailer-urls.cypher"
echo "3. Coller et exécuter chaque requête"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "📺 URLs de bandes-annonces disponibles:"
echo ""
echo "✓ The Matrix"
echo "✓ Inception"
echo "✓ The Dark Knight"
echo "✓ Interstellar"
echo "✓ The Shawshank Redemption"
echo "✓ Pulp Fiction"
echo "✓ Fight Club"
echo "✓ The Godfather"
echo "✓ Forrest Gump"
echo "✓ Avatar"
echo "✓ Titanic"
echo "✓ Gladiator"
echo "✓ Spider-Man: No Way Home"
echo "✓ Joker"
echo "✓ Black Panther"
echo "✓ Oppenheimer"
echo "✓ The Batman"
echo "✓ John Wick"
echo "✓ Parasite"
echo "✓ Et plus..."
echo ""
echo "💡 Les autres films auront une vidéo de démo par défaut"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
read -p "Voulez-vous exécuter le script maintenant? (o/n) " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Oo]$ ]]
then
    echo "🚀 Lancement du script..."
    ./scripts/add-trailers.sh
else
    echo "👋 Script annulé. Vous pouvez l'exécuter plus tard avec:"
    echo "   ./scripts/add-trailers.sh"
fi
