#!/bin/bash

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║     DÉMARRAGE MANUEL SERVICES NEO4FLIX - ÉTAPE PAR ÉTAPE    ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

PROJECT_DIR="/home/pro12x/Desktop/Projects/01Dakar/Java/neo4flix"

echo "📋 INSTRUCTIONS:"
echo ""
echo "Ouvrez 6 NOUVEAUX TERMINAUX et exécutez dans chacun:"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "TERMINAL 1 - Eureka Server (Port 8761):"
echo "═══════════════════════════════════════════════════════════════"
echo "cd $PROJECT_DIR/eureka-server"
echo "mvn spring-boot:run"
echo ""
echo "⏳ ATTENDRE 30 secondes que Eureka démarre complètement!"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "TERMINAL 2 - API Gateway (Port 8080):"
echo "═══════════════════════════════════════════════════════════════"
echo "cd $PROJECT_DIR/api-gateway"
echo "mvn spring-boot:run"
echo ""
echo "⏳ ATTENDRE 20 secondes"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "TERMINAL 3 - User Service (Port 1112):"
echo "═══════════════════════════════════════════════════════════════"
echo "cd $PROJECT_DIR/user-service"
echo "mvn spring-boot:run"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "TERMINAL 4 - Movie Service (Port 1113):"
echo "═══════════════════════════════════════════════════════════════"
echo "cd $PROJECT_DIR/movie-service"
echo "mvn spring-boot:run"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "TERMINAL 5 - Rating Service (Port 1114):"
echo "═══════════════════════════════════════════════════════════════"
echo "cd $PROJECT_DIR/rating-service"
echo "mvn spring-boot:run"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "TERMINAL 6 - Recommendation Service (Port 1115):"
echo "═══════════════════════════════════════════════════════════════"
echo "cd $PROJECT_DIR/recommendation-service"
echo "mvn spring-boot:run"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "✅ APRÈS DÉMARRAGE DE TOUS LES SERVICES:"
echo ""
echo "1. Vérifier Eureka Dashboard:"
echo "   → http://localhost:8761"
echo "   → Tous les 5 services doivent apparaître comme UP"
echo ""
echo "2. Tester API Gateway:"
echo "   → curl http://localhost:1111/actuator/health"
echo ""
echo "3. Démarrer le frontend Angular:"
echo "   → cd $PROJECT_DIR/neo4flix-ui"
echo "   → npm start"
echo ""
echo "4. Accéder à l'application:"
echo "   → http://localhost:4200"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "⚠️  IMPORTANT:"
echo "  • Attendre 30-45 secondes après le dernier service"
echo "  • Vérifier Eureka avant de tester le frontend"
echo "  • Garder tous les terminaux ouverts"
echo ""
echo "🛑 Pour arrêter tous les services:"
echo "   pkill -f 'spring-boot:run'"
echo ""
echo "═══════════════════════════════════════════════════════════════"
